#!/usr/bin/env bash

selected=$(find $HOME/Dev -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

# echo "$selected $selected_name

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

# create a new session and switch to it 
tmux new-session -ds $selected_name -c $selected
switch_to
tmux send-keys -t $selected_name "./ready-tmux" Enter
